### PR TITLE
Custom parallel.for loop 

### PR DESCRIPTION
**Pull request by MarkusKuntner**
Allows a parallelization without a partitioner and the results are even more deterministic because the summation takes place in the same order
In addition, more than 64 processor cores can be used for the dispersion module

### CODE REVIEW

**Comment by JoshLovesFun** [comment]
I hope to be able to test this before Thursday. I am excited to see the results and will let you know when I have done so!

**Comment by JoshLovesFun** [comment]
I have tested this new version of GRAL with 1 point source, a building, and a few receptors.
I have tested it with the following number of processors with deterministic mode activated: 1, 3, 4, 7, and 8.
I have found identical concentrations between runs when using the same number of processors.
I have also found identical concentrations between runs while using different number of processors, i.e., comparing 3 processors to 7.

Have we finally achieved our goal? Thanks!

**Review by JoshLovesFun — COMMENTED** [review]
Looks good

**Comment by MarkusKuntner** [comment]
Yes, it looks quite good. In the next step, I would like to compare the performance of Parallel.For and our CustomParallelFor function.

**Comment by JoshLovesFun** [comment]
@MarkusKuntner I have tested the performance of the Parallel.For and the CustomParallelFor using deterministic mode and non-deterministic (Non-determ..) mode. The CustomParallelFor is the latest version of the code, and the Parallel.For is based on commit hash 5e32300.
I also tested the official release version of GRAL (May 3rd).
I did some final tests to verify the stability of my computer and I found some differences in run time because of computer processing fluctuations/available computer resources so the numbers below are estimates. I am using Windows 11, .NET8 desktop runtime, and not using the AVX512 instructions.
Note also that in visual studio, I compiled "debug" versions for the versions of GRAL we have been testing. I am not sure what was done for the official release. Maybe "release" versions are a bit faster?

These results are based on 1 point source, 1 simple building, 600 second dispersion time, and 400 particles per second. Domain size is about 1500 by 1500 meters. The times below are in seconds based on terminal output.

**1 Processor:**
- Deterministic 5e32300 - Dispersion 23.5, Flow Field 43.9
- Deterministic Custom -  Dispersion 24.2, Flow Field 44.5
- Non-determ.. 5e32300 - Dispersion 23.7, Flow Field 30.7
- Non-determ.. Custom  - Dispersion 23.7, Flow Field 30.4

**4 Processors:**
- Deterministic 5e32300 - Dispersion 7.5, Flow Field 38.3
- Deterministic Custom -  Dispersion 7.6 Flow Field 39.5
- Non-determ.. 5e32300 - Dispersion 7.5, Flow Field 15.7
- Non-determ.. Custom  - Dispersion 7.3, Flow Field 15.4

**8 Processors:**
- Deterministic 5e32300 test 1 - Dispersion 5.0, Flow Field 37.6
- Deterministic 5e32300 test 2 - Dispersion 5.2, Flow Field 38.4
- Deterministic 5e32300 test 3 - Dispersion 5.2, Flow Field 37.8
- Deterministic 5e32300 test 4 - Dispersion 4.8, Flow Field 38.1
- Deterministic 5e32300 test 5 - Dispersion 5.4, Flow Field 38.3
- Deterministic Custom test 1 -  Dispersion 4.9 Flow Field 37.5
- Deterministic Custom test 2 -  Dispersion 5.2 Flow Field 38.9
- Deterministic Custom test 3 -  Dispersion 5.0 Flow Field 38.5
- Deterministic Custom test 4 -  Dispersion 4.8 Flow Field 37.2
- Deterministic Custom test 5 -  Dispersion 5.2 Flow Field 37.7
- Non-determ.. 5e32300 test 1 - Dispersion 5.3, Flow Field 11.8
- Non-determ.. 5e32300 test 2 - Dispersion 5.0, Flow Field 11.5
- Non-determ.. 5e32300 test 3 - Dispersion 5.0, Flow Field 11.7
- Non-determ.. Custom test 1 - Dispersion 4.8, Flow Field 11.8
- Non-determ.. Custom test 2 - Dispersion 5.0, Flow Field 11.8
- Non-determ.. Custom test 3 - Dispersion 5.1, Flow Field 11.9
- Non-determ.. May 3rd test 1 - Dispersion 4.6, Flow Field 11.7
- Non-determ.. May 3rd test 2 - Dispersion 4.6, Flow Field 11.6
- Non-determ.. May 3rd test 3 - Dispersion 4.6, Flow Field 11.5
- Non-determ.. May 3rd test 4 - Dispersion 4.8, Flow Field 11.6
- Non-determ.. May 3rd test 5 - Dispersion 4.5, Flow Field 11.6
- Non-determ.. May 3rd debug test 1 - Dispersion 4.9, Flow Field 11.9
- Non-determ.. May 3rd debug test 2 - Dispersion 4.9, Flow Field 11.5
- Non-determ.. May 3rd debug test 3 - Dispersion 5.1, Flow Field 11.7

Josh

**Comment by MarkusKuntner** [comment]
@JoshLovesFun thank you very much for your tests. Here are my results. I think that this version could be part of the GRAL development path.
### Environment/Projekt settings
Windows Server 2022
Line and area sources
5 Source groups
300 Particles per second, 3600 s dispersion time
694 x 564 cells, cell size 3 x 3 m
48 processor cores
Both versions are compiled in release mode. I have noticed a slight performance regression for the Custom.Parallel.For version when running multiple GRAL instances. For single instances, however, Cusom.Parallel.For seems to be even slightly faster.

| Situation    | Dispersion [s] Non-determ. [5e32300](https://github.com/JoshLovesFun/GRAL-Explore/commit/5e32300563dfd18fc8296b6e05edd245573b7426)| Dispersion [s] Non-determ. Custom | Flow Field [s] Non-determ. [5e32300](https://github.com/JoshLovesFun/GRAL-Explore/commit/5e32300563dfd18fc8296b6e05edd245573b7426) | Flow Field [s] Non-determ. Custom|
| :----------- | :-------------- | -------------: | -------------: |  -------------: |
| 1  |  23.6| 23.9|68.1 | 67.8 |
| 2  |  27.0| 24.9| 67.0 |66.6|
| 3  |   9.7| 8.5| 67.3 | 66.5 |
| 4  | 16.6| 14.6| 66.8 |66.5|

**Comment by JoshLovesFun** [comment]
Nice. Those results look good. Thanks for your tests as well. A deterministic GRAL can also be helpful for some regulatory applications.

**Pull request merged**
