### PR TITLE
Deterministic diagnostic flow field calculation and keep compatibility

### PR DESCRIPTION
**Pull request by MarkusKuntner**
The diagnostic flow field calculation needs to be calculated sequential for deterministic results 
The prognostic calculation should work as before without the additional option
Current tests are also successful using larger domain areas
@JoshLovesFun, thank you very much for the tests. I am looking forward to the results.

### CODE REVIEW

**Comment by JoshLovesFun** [comment]
Will merge and review shortly.

**Comment by JoshLovesFun** [comment]
@MarkusKuntner I have done some simple testing with a small domain, 1 building, and 1 stack. The switch works correctly. With 1 processor, I got identical model results, and with multiple processors (6 and 8 tested), I got nearly identical results. It looked like maybe only the 2nd or 3rd digit after the decimal was different. This result is very great news. I still wonder why there is the slight difference, considering you have made some of the operations serial instead of parallel so there shouldn't be the stripe combination problem? The processing time was about 3.7 times longer (in my single test case) in deterministic mode which is understandable.
One thing I did happen to notice is difference in the console result display when the deterministic switch is on or off. Note the missing slab height in the image comparison below.

Deterministic:
image
Non-Deterministic:
image

I got a bit confused earlier with multiple branches open, but I think I sorted it out correctly and this is the latest.

Josh

**Comment by MarkusKuntner** [comment]
@JoshLovesFun,  we are really close to our goal. I can't really explain the small differences, but there are still quite a few processes running in parallel, so despite synchronization using Lock{}, I cannot completely guarantee that there won't be small deviations. A test with a single processor gave exactly the same results. There might be race conditions. This could perhaps be improved in .NET9 with System.Threading.Lock [https://github.com/dotnet/runtime/issues/34812](https://github.com/dotnet/runtime/issues/34812) Do you have experience with (fast) synchronization of parallel processes (a global lock object slows down the calculation)? 
The console output was a duplicate, I removed it.

**Comment by JoshLovesFun** [comment]
Unfortunately I don't have much experience with this, but I was reading about this before I brought the code to GitHub. I tried a code like this:

```csharp
internal static class ThreadSafeRandom
{
    [ThreadStatic]
    private static Random? _local;

    private static Random Instance => _local ??= new Random(Consts.ConstRandSeed);

    public static double FixedRandNextDouble()
    {
        return Instance.NextDouble();
    }
    public static int FixedRandNext()
    {
        return Instance.Next(0, 9000000) + 1000000;
    }
}
```

and I saw a post on how it could be done:
https://stackoverflow.com/questions/19270507/correct-way-to-use-random-in-multithread-application
However, in both cases, I couldn't get it to work, but my understanding of C# as a whole is not great so maybe it is possible to work with this.

**Comment by JoshLovesFun** [comment]
Although I realize that the issue may not be directly related to the deterministic number generator.

**Comment by JoshLovesFun** [comment]
I had previously completely removed all random number generation from the code and replaced all fixed or varying seeds with a constant value. Even so, I thought I was able to achieve similar results to what we have now. So race conditions are possible and perhaps difficult to track down.

**Comment by MarkusKuntner** [comment]
Race condition can occure the code parts where the concentrations are summed up in parallel threads, for example
```
lock (conz3d_L)
{
     conz3d_L[SG_nteil] += (float)conc;
}
```
Despite lock, caching problems (CPU cache) can occur.  Perhaps the problem could be solved using Volatile. The question is, of course, what effect this will have on performance when cpu chaching is disabled by the Volatile keyword.
The “Interlocked” class would be atomic, but not, if the variable itself has to be summed up, as with

`Interlocked.Exchange (ref conz3d_L[SG_nteil], conz3d_L[SG_nteil] + (float) conc);`

I have read numerous comments and instructions, but avoiding race conditions in such cases seems to be difficult. With multiple sources and area as well as line sources, the error becomes smaller, because the particles occupy the same cell less frequently (and if so, not at the same time).

This version is so exciting that I want to add it to a separate branch in the GRAL repo. Whether it will be included in a release is not up to me.

**Comment by MarkusKuntner** [comment]
After some further considerations and tests, I came to the conclusion that the issue is not due to race conditions, but to simple rounding effects.
Floating-point types have a precision of 6 to 9 digits. The (exact) result depends on the order in which the values are added. This sounds strange at first, but can be explained if you take a closer look at how floating point numbers are stored (sign, exponent, mantissa). 
The following small program returns the following results: 
```
Up   8,8874655
Down 8,887466
```
Here is the source code:
```
double[] arr = new double[] {Math.PI, Math.PI / 2, Math.PI / 3, Math.PI / 4, Math.PI / 5, Math.PI / 6, Math.PI / 7, Math.PI / 8, Math.PI / 9};    
float sumUp = 0; float sumDown = 0;
for (int i = 0; i < arr.Length; i++) { sumUp += (float) arr[i];}
for (int i = arr.Length - 1; i >= 0; i--) { sumDown += (float) arr[i];}
Console.WriteLine("Up   " + sumUp);
Console.WriteLine("Down " + sumDown);
Console.ReadKey();
```
Using parallel processing, the sequence of the individual concentration parts to be added can vary arbitrarily. This results in these rounding issues.


This version is so exciting that I want to add it to a separate branch in the GRAL repo. Whether it will be included in a release is not up to me.

**Comment by JoshLovesFun** [comment]
The deterministic version of GRAL would indeed be very nice if it can be added into a future release!

**Comment by JoshLovesFun** [comment]
Thanks for investigating this. I remember reading about addition not being associate for floating point numbers. I didn't really understand, but your explanation helps.

So I guess there are 3 solutions I can think of now:

1) Switch the floats to doubles. This could reduce the final differences in the sums, and the output of the results after rounding between runs may be negligible?This would increase memory usage I assume, but I am not sure how big of a restriction memory is for GRAL on modern computers.

2) Somehow track the processor ID, and always perform the addition in the same order between processors. This could work, but there would still be different results depending on how many processors are used for each model run.

3) Perhaps use the double precision method, and round the final output as needed.

**Comment by MarkusKuntner** [comment]
Memory usage is an issue for many users, which was the reason for using float arrays. Many users use several evaluation layers and, above all, numerous source groups. We even get user requests asking whether the memory requirement could be reduced. In principle, there are certainly approaches for this, but the costs would be longer computing times. This therefore makes sense for a test version, but is currently not suitable for the main branch.

**Comment by JoshLovesFun** [comment]
I see. I was wondering why there were many cases of float used instead of double. Most of our applications we have tested don't have many sources or evaluation layers, but I understand the importance of this.

**Pull request merged**
